
#     _   _      _   _                ____     _ _ _
#    | \ | | ___| |_| |__   ___ _ __ / ___|___(_) (_)_ __   __ _
#    |  \| |/ _ \ __| '_ \ / _ \ '__| |   / _ \ | | | '_ \ / _` |
#    | |\  |  __/ |_| | | |  __/ |  | |__|  __/ | | | | | | (_| |
#    |_| \_|\___|\__|_| |_|\___|_|   \____\___|_|_|_|_| |_|\__, |
#                                                by xGinko |___/
config-version: 1.0

language:
  default-language: en_us
  # if set to true, will display language based on client locale
  auto-language: true

general:
  prevent-building:
    enable: false
    teleport-down-on-blockplace: false
  prevent-moving:
    enable: false
    surround-with-netherrack: false
  prevent-teleporting:
    enable: false
    remove-ender-pearls: false
  prevent-flying:
    enable: false

teleport-from-nether-ceiling-settings:
  # This option can also be enabled via permission: netherceiling.safeteleport
  # Teleports player downwards, creating a safe airpocket where they can then free
  # themselves. Checks for air below feet and lava.
  safely-teleport-players: true
  # The distance in blocks the player will be teleported downwards. Recommended to leave
  # at 7 if using in combination with safe teleport, so players don't abuse the plugin
  # to delete bedrock.
  downwards-distance-in-blocks: 7

portals:
  prevent-creating-portals:
    enable: false
    # configure message in lang file
    show-actionbar: true
  prevent-using-portals-on-ceiling:
    # If enabled will cancel the teleport when a player attempts to use a portal on the ceiling.
    enable: false
    # configure message in lang file
    show-actionbar: true
  prevent-using-portals-to-ceiling:
    # If enabled will cancel teleport if a player tries to use a portal that is connected to
    # a portal on the nether ceiling.
    enable: false
    # configure message in lang file
    show-actionbar: true

building:
  # Enables players to use water buckets on the ceiling. (woah illegal water in the nether)
  enable-placing-water: false
  # Enables players to use beds like respawn anchors on the nether ceiling.
  enable-using-beds: false
  custom-build-height:
    enable: true
    height: 256
  blacklist-specific-materials:
    # Prevents placement of specific materials configured below.
    enable: false
    use-as-whitelist-instead: false
    material:
      - BOAT
      - SOUL_SAND
      - ICE
  limit-specific-blocks:
    # Like a chunk limit, except it will only count blocks above the nether ceiling.
    enable: false
    blocks:
      SOUL_SAND: 25
      OBSIDIAN: 10

entities:
  disable-all-non-player-entity-spawns: false
  disable-specific-entity-spawns:
    enable: false
    use-as-whitelist-instead: false
    entities:
      - GHAST
      - ZOMBIE_PIGLIN
  entity-limits-per-ceiling-chunk:
    # Counts only entities above the nether ceiling.
    enable: false
    entities:
      # Add or delete as many entries as you want.
      MULE: 5
      PIG: 4
      HORSE: 2
      BOAT: 4

vehicles:
  # Will also eject players from their vehicles if they mounted it below and then go on top.
  prevent-using-specific-vehicles:
    enable: false
    use-as-whitelist-instead: false
    vehicles:
      - BOAT
      - HORSE
      - DONKEY
      - MULE

potions:
  remove-specific-potion-effects:
    enable: false
    show-actionbar: false
    use-as-whitelist-instead: false
    potion-effects:
      - SPEED
  nerf-specific-potion-effects:
    enable: false
    show-actionbar: false
    potion-effects:
      # Add or delete as many entries as you want. They will need to be formatted like the examples though.
      SPEED:
        max-potency: 1
        max-duration: 600
      REGENERATION:
        max-potency: 2
        max-duration: 200