
#     _   _      _   _                ____     _ _ _
#    | \ | | ___| |_| |__   ___ _ __ / ___|___(_) (_)_ __   __ _
#    |  \| |/ _ \ __| '_ \ / _ \ '__| |   / _ \ | | | '_ \ / _` |
#    | |\  |  __/ |_| | | |  __/ |  | |__|  __/ | | | | | | (_| |
#    |_| \_|\___|\__|_| |_|\___|_|   \____\___|_|_|_|_| |_|\__, |
#                                                by xGinko |___/
config-version: 1.0

language:
  default-language: en_us
  # if set to true, will display language based on client locale
  auto-language: true

general:
  prevent-building:
    enable: false
    show-actionbar: true
    teleport-down-on-blockplace: false
  prevent-moving:
    enable: false
    show-actionbar: true
    teleport-down-on-move: false
  prevent-teleporting-up:
    enable: false
    show-actionbar: true

teleport-from-nether-ceiling-settings:
  # This option can also be enabled via permission: netherceiling.safeteleport
  # Teleports player downwards, creating a safe airpocket where they can then free
  # themselves. Checks for air below feet and lava.
  safely-teleport-players: true
  # The distance in blocks the player will be teleported downwards. Recommended to leave
  # at 7 if using in combination with safe teleport, so players don't abuse the plugin
  # to delete bedrock.
  downwards-distance-in-blocks: 7

portals:
  prevent-creating-portals:
    enable: false
    # configure message in lang file
    show-actionbar: true
  prevent-using-portals-on-ceiling:
    # If enabled will cancel the teleport when a player attempts to use a portal on the ceiling.
    enable: false
    # configure message in lang file
    show-actionbar: true
  prevent-using-portals-to-ceiling:
    # If enabled will cancel teleport if a player tries to use a portal that is connected to
    # a portal on the nether ceiling.
    enable: false
    # configure message in lang file
    show-actionbar: true

building:
  # Enables players to use water buckets on the ceiling. (woah illegal water in the nether)
  enable-placing-water:
    enable: false
    strike-lightning-on-water-place: false
  # Enables players to use beds like respawn anchors on the nether ceiling.
  enable-using-beds: false
  custom-build-height:
    enable: true
    show-actionbar: true
    height: 320
  blacklist-specific-blocks:
    # Prevents placement of specific materials configured below.
    enable: false
    show-actionbar: true
    use-as-whitelist-instead: false
    blocks:
      - SOUL_SOIL
      - SOUL_SAND
      - BLUE_ICE
      - PACKED_ICE
      - ICE
  limit-specific-blocks:
    # Like a chunk limit, except it will only count blocks above the nether ceiling.
    enable: false
    show-actionbar: true
    blocks:
      SOUL_SAND: 25
      OBSIDIAN: 10

fast-blocks:
  # Fast blocks are blocks like Ice or Soul Sand where an entity or player can accelerate higher than on regular blocks.
  player-speed:
    enable: false
    max-speed-in-bps: 7.1
    show-actionbar: true
    fast-blocks:
      - SOUL_SOIL
      - SOUL_SAND
      - BLUE_ICE
      - PACKED_ICE
      - ICE
  vehicle-speed:
    enable: false
    max-speed-in-bps: 15.5
    show-actionbar-to-nearby-players: true
    fast-blocks:
      - BLUE_ICE
      - PACKED_ICE
      - ICE
    vehicles:
      - BOAT
      - CHEST_BOAT

illegals:
  remove-specific-blocks:
    on-chunkload:
      enable: false
      pause-on-low-TPS: true
      pause-TPS: 16
      use-as-whitelist-instead: false
      specific-blocks:
        - SOUL_SAND
        - SOUL_SOIL
        - ICE
        - PACKED_ICE
        - BLUE_ICE
      exempted-worlds:
        - exampleworld1
        - exampleworld2
    periodically:
      enable: false
      check-period-in-seconds: 30
      pause-on-low-TPS: true
      pause-TPS: 16
      use-as-whitelist-instead: false
      specific-blocks:
        - SOUL_SAND
        - SOUL_SOIL
        - ICE
        - PACKED_ICE
        - BLUE_ICE
      exempted-worlds:
        - exampleworld1
        - exampleworld2
  remove-all-blocks:
    on-chunkload:
      enable: false
      pause-on-low-TPS: true
      pause-TPS: 16
      exempted-worlds:
        - exampleworld1
        - exampleworld2
    periodically:
      enable: false
      check-period-in-seconds: 30
      pause-on-low-TPS: true
      pause-TPS: 16
      exempted-worlds:
        - exampleworld1
        - exampleworld2


entities:
  disable-all-non-player-entity-spawns: false
  disable-specific-entity-spawns:
    enable: false
    use-as-whitelist-instead: false
    entities:
      - GHAST
      - ZOMBIFIED_PIGLIN
  entity-limits-per-ceiling-chunk:
    # Counts only entities above the nether ceiling.
    enable: false
    log: true
    check-period-in-ticks: 20
    entities:
      # Add or delete as many entries as you want.
      MULE: 5
      PIG: 4
      HORSE: 2
      BOAT: 4

vehicles:
  # Will also eject players from their vehicles if they mounted it below and then go on top.
  prevent-using-specific-vehicles:
    enable: false
    show-actionbar: true
    use-as-whitelist-instead: false
    vehicles:
      - BOAT
      - HORSE
      - DONKEY
      - MULE

potions:
  remove-specific-potion-effects:
    enable: false
    show-actionbar: false
    use-as-whitelist-instead: false
    potion-effects:
      - SPEED
  nerf-specific-potion-effects:
    enable: false
    show-actionbar: false
    # Format: PotionEffectType,Maximum Potency,Maximum Duration in Ticks
    potion-effects:
      - SPEED,1,1200
      - REGENERATION,1,200